//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 09:57:17 AM CST 
//

package net.easipay.wgq.ep.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}id"/>
 *         &lt;element ref="{}billNo" minOccurs="0"/>
 *         &lt;element ref="{}status"/>
 *         &lt;element ref="{}remark" minOccurs="0"/>
 *         &lt;element ref="{}reserve" minOccurs="0"/>
 *         &lt;element ref="{}replyNote" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "id", "billNo", "status", "remark",
		"reserve", "replyNote" })
@XmlRootElement(name = "ReturnInfo")
public class ReturnInfo {

	@XmlElement(required = true)
	protected String id;
	protected String billNo;
	@XmlElement(required = true)
	protected String status;
	protected String remark;
	protected String reserve;
	protected String replyNote;

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		this.id = value;
	}

	/**
	 * Gets the value of the billNo property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBillNo() {
		return billNo;
	}

	/**
	 * Sets the value of the billNo property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBillNo(String value) {
		this.billNo = value;
	}

	/**
	 * Gets the value of the status property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStatus(String value) {
		this.status = value;
	}

	/**
	 * Gets the value of the remark property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * Sets the value of the remark property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRemark(String value) {
		this.remark = value;
	}

	/**
	 * Gets the value of the reserve property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReserve() {
		return reserve;
	}

	/**
	 * Sets the value of the reserve property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setReserve(String value) {
		this.reserve = value;
	}

	/**
	 * Gets the value of the replyNote property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReplyNote() {
		return replyNote;
	}

	/**
	 * Sets the value of the replyNote property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setReplyNote(String value) {
		this.replyNote = value;
	}

}
